"""Subtext derivation — materialize a filtered child project from a parent's kept layers.

Keeping an "extraction" type-layer (e.g. ``chapter``) pulls those element spans' text into a
new child project. Every parent layer that OVERLAPS the kept spans — the ``book``/``volume``/
``body`` containers, the verse-number index, and annotation tracks — is remapped onto the
child through a single piecewise offset map, preserving each layer's mask state (verse numbers
stay masked, exactly as in the parent). Non-overlapping elements (headers, front matter) fall
away. The child is an ordinary project (built via the standard ingest pipeline) plus a parent
link in its metadata.
"""
from __future__ import annotations

import bisect
import dataclasses
import json
from collections.abc import Callable
from pathlib import Path
from typing import TYPE_CHECKING, Any

from palimpsest.atomic import atomic_write_text
from palimpsest.layout import LayoutConfig, LayoutSection, load_layout, save_layout

if TYPE_CHECKING:
    from palimpsest.project import Project

SEPARATOR = "\n\n"

# Tracks that are structural/derived and must NOT be naively offset-remapped: segments and
# sections are regenerated by ingest; elements is regenerated from the layout; verses is
# remapped specially (it carries book/chapter/verse metadata).
_SKIP_TRACKS = {"segments", "sections", "elements", "verses"}


class OffsetMap:
    """Piecewise parent→child offset translation over ordered, disjoint kept spans.

    Child text is ``SEPARATOR.join(parent_text[s:e] for (s,e) in spans)``; this maps a parent
    offset to its child offset, and maps a parent element to the single child element spanning
    its overlapped kept region (including the separator gaps between kept spans).

    Precondition (enforced in ``__init__``): ``spans`` is ordered, mutually disjoint, and each is
    non-empty (``0 <= start < end``) — the kept-spans contract produced by ``_complement_spans``
    and :func:`compute_kept_spans`. The bisect-based translators are correct *only* under this
    precondition, so a malformed span set raises ``ValueError`` at construction instead of
    silently mistranslating every offset. Round-trip: for any parent offset inside a kept span,
    ``inverse_point(translate_point(off)) == off``.
    """

    def __init__(self, spans: list[tuple[int, int]], sep_len: int) -> None:
        self.spans = spans
        self.sep_len = sep_len
        # Parallel start/end arrays let the forward translators binary-search instead of
        # linear-scan — critical when remapping the segments track (10⁵ records) over 10³ kept
        # spans. The same pass enforces the ordered/disjoint/non-empty precondition the bisect
        # logic depends on (see class docstring).
        self._starts = [s for s, _ in spans]
        self._ends = [e for _, e in spans]
        self.base: list[int] = []
        cursor = 0
        prev_end = 0
        for i, (s, e) in enumerate(spans):
            if not (0 <= s < e):
                raise ValueError(f"OffsetMap span ({s}, {e}) is empty or negative")
            if s < prev_end:
                raise ValueError(
                    f"OffsetMap spans must be ordered and disjoint: ({s}, {e}) overlaps "
                    f"prior end {prev_end}"
                )
            prev_end = e
            self.base.append(cursor)
            cursor += (e - s) + (sep_len if i < len(spans) - 1 else 0)
        self.child_len = cursor

    def translate_point(self, off: int) -> int | None:
        """Child offset for a parent offset inside a kept span, else None (in a dropped gap)."""
        i = bisect.bisect_right(self._starts, off) - 1
        if i < 0:
            return None
        s, e = self.spans[i]
        # Inclusive of the exclusive end e on purpose: this also translates half-open range *endpoints*
        # (remap_verses passes each verse's e), which must map to the child offset one past the span's
        # last kept char. A genuine in-gap offset is already off > e here and returns None.
        return self.base[i] + (off - s) if off <= e else None

    def remap_element(self, a: int, e: int) -> tuple[int, int] | None:
        """Child [start,end) for a parent element [a,e), spanning every kept span it overlaps
        (separator gaps included), or None if it touches no kept span."""
        # First span with end > a; last span with start < e. On disjoint, ordered spans the
        # overlap set is exactly the contiguous index range [i0, iN].
        i0 = bisect.bisect_right(self._ends, a)
        iN = bisect.bisect_left(self._starts, e) - 1
        if i0 > iN or i0 >= len(self.spans) or iN < 0:
            return None
        s0 = self._starts[i0]
        sN, eN = self.spans[iN]
        cs = self.base[i0] + (max(a, s0) - s0)
        ce = self.base[iN] + (min(e, eN) - sN)
        return (cs, ce)

    def _segment_at(self, child_off: int) -> int | None:
        """Index of the kept span whose CONTENT (excluding the following separator) contains
        ``child_off``, or ``None`` if it lands in an inter-span separator. O(log n)."""
        i = bisect.bisect_right(self.base, child_off) - 1
        if i < 0:
            return None
        s, e = self.spans[i]
        return i if child_off <= self.base[i] + (e - s) else None

    def inverse_point(self, child_off: int) -> int | None:
        """Parent offset for a child offset (the inverse of :meth:`translate_point`), or ``None``
        if it falls inside an inter-span separator with no parent pre-image."""
        i = self._segment_at(child_off)
        if i is None:
            return None
        return self.spans[i][0] + (child_off - self.base[i])

    def inverse_element(self, cs: int, ce: int) -> tuple[int, int] | None:
        """Parent [start,end) for a child [start,end) that lies within a SINGLE kept span, or
        ``None`` if it spans a separator (a dropped parent gap) and has no contiguous pre-image."""
        i = self._segment_at(cs)
        if i is None:
            return None
        s, e = self.spans[i]
        seg_end = self.base[i] + (e - s)
        if ce > seg_end:
            return None
        return (s + (cs - self.base[i]), s + (ce - self.base[i]))

    def inverse_span(self, cs: int, ce: int) -> tuple[int, int] | None:
        """Parent [start,end) for a child [start,end), KEEPING ranges that span excised gaps.

        If the child range lies in one kept span it maps exactly (:meth:`inverse_element`). If it
        bridges one or more excised masked gaps, it maps to the original span from its first to its
        last character — so the (now-greyed) masked content sits inside the returned range, exactly
        the "as if it weren't there" semantics analysis windows want. ``None`` only for an empty or
        out-of-range child range."""
        exact = self.inverse_element(cs, ce)
        if exact is not None:
            return exact
        if ce <= cs:
            return None
        a = self.inverse_point(cs)
        b = self.inverse_point(ce - 1)
        if a is None or b is None:
            return None
        return (a, b + 1)


def compute_kept_spans(
    sections: list[LayoutSection],
    extraction_types: set[str],
    excluded_ids: set[str],
    container_spans: list[tuple[int, int]] | None = None,
) -> list[tuple[int, int]]:
    """Ordered, merged spans of the extraction-layer elements (minus Stage-2 exclusions).

    When ``container_spans`` is non-empty, only elements lying fully within one of those container
    ranges are kept — geometric scoping (e.g. "only the Appendix books") that works directly off the
    section ranges, independent of the (often-unpopulated) ``parent_id`` field."""

    def _in_scope(s: int, e: int) -> bool:
        return not container_spans or any(cs <= s and e <= ce for cs, ce in container_spans)

    raw = sorted(
        (s.start, s.end)
        for s in sections
        if s.type in extraction_types and s.id not in excluded_ids and s.start < s.end
        and _in_scope(s.start, s.end)
    )
    merged: list[tuple[int, int]] = []
    for s, e in raw:
        if merged and s <= merged[-1][1]:
            merged[-1] = (merged[-1][0], max(merged[-1][1], e))
        else:
            merged.append((s, e))
    return merged


def assemble_text(parent_text: str, spans: list[tuple[int, int]], sep: str = SEPARATOR) -> str:
    return sep.join(parent_text[s:e] for s, e in spans)


def remap_layout(
    sections: list[LayoutSection],
    mask_by_type: dict[str, bool],
    extra_types: list[dict[str, Any]],
    omap: OffsetMap,
) -> LayoutConfig:
    """Carry every parent layout element overlapping a kept span onto the child, remapped and
    with its mask state preserved. Parent-id references to dropped elements are cleared."""
    out: list[LayoutSection] = []
    kept_ids: set[str] = set()
    for s in sections:
        m = omap.remap_element(s.start, s.end)
        if m is None or m[1] <= m[0]:
            continue
        kept_ids.add(s.id)
        out.append(dataclasses.replace(s, start=m[0], end=m[1]))
    for s in out:
        if s.parent_id is not None and s.parent_id not in kept_ids:
            s.parent_id = None
    return LayoutConfig(
        sections=out, mask_by_type=dict(mask_by_type), applied=True, extra_types=list(extra_types or [])
    )


def remap_verses(records: list[dict[str, Any]], omap: OffsetMap) -> list[dict[str, Any]]:
    """Carry verse-index records within kept spans, remapping their ns/s/e offsets and keeping
    book/chapter/verse metadata so the child's verse-number layer stays masked as in the parent."""
    out: list[dict[str, Any]] = []
    for r in records:
        ns, s, e = omap.translate_point(r["ns"]), omap.translate_point(r["s"]), omap.translate_point(r["e"])
        if ns is None or s is None or e is None:
            continue
        out.append({**r, "ns": ns, "s": s, "e": e})
    return out


def remap_track_annotations(annotations: list[dict[str, Any]], omap: OffsetMap) -> list[dict[str, Any]]:
    """Remap W3C annotations fully within kept spans (drop any crossing a dropped gap)."""
    out: list[dict[str, Any]] = []
    for ann in annotations:
        sel = (ann.get("target") or {}).get("selector") or {}
        a, e = sel.get("start"), sel.get("end")
        if not isinstance(a, int) or not isinstance(e, int):
            continue
        m = omap.remap_element(a, e)
        if m is None or (m[1] - m[0]) != (e - a):  # length change ⇒ crossed a dropped gap
            continue
        new = json.loads(json.dumps(ann))
        new["target"]["selector"]["start"] = m[0]
        new["target"]["selector"]["end"] = m[1]
        out.append(new)
    return out


def remap_result_annotations(annotations: list[Any], omap: OffsetMap) -> list[Any]:
    """Re-anchor extractor-produced Annotation objects from analyzable to original coordinates.

    Each annotation's ``TextPositionSelector`` is mapped back through the OffsetMap (the inverse of
    materializing the analyzable text); an annotation straddling a dropped masked gap has no
    contiguous original image and is dropped. Quote-only selectors (no offsets) pass through."""
    from palimpsest.annotation.model import TextPositionSelector

    out: list[Any] = []
    for ann in annotations:
        sel = getattr(getattr(ann, "target", None), "selector", None)
        if isinstance(sel, TextPositionSelector):
            m = omap.inverse_span(sel.start, sel.end)
            if m is None:
                continue
            sel.start, sel.end = m
        out.append(ann)
    return out


def inverse_remap_annotation_dicts(records: list[dict[str, Any]], omap: OffsetMap) -> list[dict[str, Any]]:
    """Remap stored W3C annotation dicts from analyzable to original coordinates, in place, keeping
    gap-spanning ranges (:meth:`OffsetMap.inverse_span`). Annotations with no usable position are
    passed through; any that map to nothing are dropped."""
    out: list[dict[str, Any]] = []
    for ann in records:
        sel = (ann.get("target") or {}).get("selector") or {}
        a, e = sel.get("start"), sel.get("end")
        if isinstance(a, int) and isinstance(e, int):
            m = omap.inverse_span(a, e)
            if m is None:
                continue
            sel["start"], sel["end"] = m
        out.append(ann)
    return out


def inverse_remap_segment_offsets(offsets: list[list[int]], omap: OffsetMap) -> list[list[int]]:
    """Remap a signal manifest's ``segment_offsets`` (``[[start,end], …]``) analyzable→original."""
    out: list[list[int]] = []
    for so in offsets:
        if len(so) >= 2:
            m = omap.inverse_span(int(so[0]), int(so[1]))
            out.append([m[0], m[1]] if m is not None else list(so))
        else:
            out.append(list(so))
    return out


_ALIGN_CHAR_SPANS = (("char_start_a", "char_end_a"), ("char_start_b", "char_end_b"))


def inverse_remap_alignments(records: list[dict[str, Any]], omap: OffsetMap) -> list[dict[str, Any]]:
    """Remap alignment records' ``char_*`` span fields analyzable→original (the ``chunk_*`` matrix
    indices are coordinate-free and left untouched)."""
    for rec in records:
        for s_key, e_key in _ALIGN_CHAR_SPANS:
            if isinstance(rec.get(s_key), int) and isinstance(rec.get(e_key), int):
                m = omap.inverse_span(rec[s_key], rec[e_key])
                if m is not None:
                    rec[s_key], rec[e_key] = m
    return records


class UnmappedCoordinateError(ValueError):
    """A signal output carries character offsets in a position the analyzable→original remap does not
    handle. Raised instead of silently writing analyzable coordinates mislabeled as original (C4/G4)."""


# The character-offset keys the remap knows how to translate, and the only positions they may legally
# occupy in a signal payload. ``segment_offsets`` is a manifest's top-level span list; the ``char_*``
# keys live one-per-record in a top-level array of alignment records. A known coordinate key found
# anywhere else (nested under ``metadata``, a graph node, …) means a producer emitted offsets the
# pipeline would pass through untranslated — a hard error, not a silent mislabel.
_SEGMENT_OFFSETS_KEY = "segment_offsets"
_DECLARED_FIELDS_KEY = "analyzable_coordinate_fields"
_ALIGN_CHAR_KEYS = frozenset(k for pair in _ALIGN_CHAR_SPANS for k in pair)
_KNOWN_COORD_KEYS = _ALIGN_CHAR_KEYS | {_SEGMENT_OFFSETS_KEY}


def _coordinate_position_is_blessed(path: list[Any], key: str, declared: frozenset[str]) -> bool:
    """True if ``key`` (a coordinate-bearing field) sits where the remap actually translates it."""
    if key == _SEGMENT_OFFSETS_KEY or key in declared:
        return path == []  # a top-level manifest field
    if key in _ALIGN_CHAR_KEYS:
        return len(path) == 1 and isinstance(path[0], int)  # a record in the top-level array
    return True


def _assert_coordinates_blessed(data: Any, declared: frozenset[str]) -> None:
    """Raise :class:`UnmappedCoordinateError` if any offset-bearing key survived in a position the
    remap does not handle — the post-remap assertion the P4 contract requires."""

    def walk(node: Any, path: list[Any]) -> None:
        if isinstance(node, dict):
            for k, v in node.items():
                if (k in _KNOWN_COORD_KEYS or k in declared) and not _coordinate_position_is_blessed(
                    path, k, declared
                ):
                    where = path or ["<root>"]
                    raise UnmappedCoordinateError(
                        f"offset-bearing field {k!r} at {where} was not remapped to original "
                        "coordinates; emit it in a handled position (top-level 'segment_offsets', or "
                        f"'char_*' per record in a top-level array) or declare it in {_DECLARED_FIELDS_KEY!r}"
                    )
                walk(v, [*path, k])
        elif isinstance(node, list):
            for i, v in enumerate(node):
                walk(v, [*path, i])

    walk(data, [])


def remap_signal_data(data: Any, omap: OffsetMap) -> bool:
    """Remap a signal payload's character offsets analyzable→original IN PLACE and assert the remap
    was total (G4/C4). Returns True if anything was remapped.

    Handled shapes: a manifest dict's top-level ``segment_offsets``; a top-level array of alignment
    records' ``char_*`` spans; and any field a manifest names in ``analyzable_coordinate_fields`` —
    the declaration hook for a novel output, whose value is a ``[start, end]`` pair or a
    ``[[start, end], …]`` span list. After remapping, :func:`_assert_coordinates_blessed` raises
    :class:`UnmappedCoordinateError` if a known offset key survived in an unhandled position, so a new
    output shape that forgot to remap fails loudly instead of mislabeling analyzable coordinates as
    original."""
    declared: frozenset[str] = frozenset()
    changed = False
    if isinstance(data, dict):
        decl = data.get(_DECLARED_FIELDS_KEY)
        if isinstance(decl, list):
            declared = frozenset(str(x) for x in decl)
        if isinstance(data.get(_SEGMENT_OFFSETS_KEY), list):
            data[_SEGMENT_OFFSETS_KEY] = inverse_remap_segment_offsets(data[_SEGMENT_OFFSETS_KEY], omap)
            changed = True
        for field in declared:
            val = data.get(field)
            if isinstance(val, list) and val and all(isinstance(x, list) for x in val):
                data[field] = inverse_remap_segment_offsets(val, omap)
                changed = True
            elif isinstance(val, list) and len(val) >= 2 and all(isinstance(x, int) for x in val[:2]):
                m = omap.inverse_span(int(val[0]), int(val[1]))
                if m is not None:
                    data[field] = [m[0], m[1], *val[2:]]
                changed = True
    elif isinstance(data, list):
        inverse_remap_alignments(data, omap)
        changed = True
    _assert_coordinates_blessed(data, declared)
    return changed


def _subtext_source_name(
    parent_id: str, extraction_types: list[str], container_ids: list[str] | None = None
) -> str:
    tag = "-".join(t for t in extraction_types) or "subtext"
    if container_ids:
        # Fold the container scope into the id so two subtexts with the same types but different
        # scopes (e.g. whole-text vs appendix-only chapters) don't collide on the same child id.
        scope = "-".join(sorted(container_ids))
        tag = f"{tag}-in-{scope}"
    return f"{parent_id}--{tag}.txt"


def _remap_tracks(
    parent_dir: Path,
    child_dir: Path,
    omap: OffsetMap,
    on_track: Callable[[int, int, str], None] | None = None,
) -> list[str]:
    """Remap each non-structural annotation track from parent to child. Returns track names written.

    ``on_track(done, total, name)`` fires after each eligible track is processed, letting callers
    report derivation progress over the (variable) annotation-track count."""
    written: list[str] = []
    src = parent_dir / "tracks"
    if not src.exists():
        return written
    dst = child_dir / "tracks"
    dst.mkdir(parents=True, exist_ok=True)
    eligible = [p for p in sorted(src.glob("*.jsonl")) if p.stem not in _SKIP_TRACKS]
    total = len(eligible)
    for i, path in enumerate(eligible, start=1):
        name = path.stem
        recs = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
        remapped = remap_track_annotations(recs, omap)
        if remapped:
            atomic_write_text(
                dst / f"{name}.jsonl",
                "\n".join(json.dumps(r) for r in remapped) + "\n",
            )
            written.append(name)
        if on_track is not None:
            on_track(i, total, name)
    return written


def _write_jsonl(path: Path, records: list[dict[str, Any]]) -> None:
    atomic_write_text(
        path, ("\n".join(json.dumps(r) for r in records) + "\n") if records else ""
    )


def _update_metadata(child_dir: Path, parent: Project, extraction_types: list[str], excluded_ids: list[str], sep: str) -> None:
    meta_path = child_dir / "metadata.json"
    meta = json.loads(meta_path.read_text(encoding="utf-8"))
    meta["parent_project_id"] = parent.metadata.id
    meta["parent_reference_sha256"] = parent.metadata.reference_sha256
    meta["ingest_method"] = "subtext_derivation"
    meta["derivation"] = {
        "extraction_types": list(extraction_types),
        "excluded_ids": list(excluded_ids),
        "separator": sep,
    }
    atomic_write_text(meta_path, json.dumps(meta, indent=2, ensure_ascii=False))


def _remap_parent_segments(parent_dir: Path, omap: OffsetMap) -> tuple[list[Any], list[Any], list[Any]]:
    """Remap the parent's segments track (paragraph/section/sentence spans) onto the child.

    Substituting this for re-running the spaCy sentence segmenter on the assembled child text is the
    main subtext-generation speedup: segmentation already happened once on the parent. A segment fully
    inside dropped content is dropped; a segment that bridges a dropped gap keeps its bridged child
    range (matching what re-segmenting the joined child text would produce). Re-indexed per type in
    document order so the child's indices are contiguous, exactly as a fresh ingest would write them."""
    from palimpsest.ingest.segmenter import Segment

    src = parent_dir / "tracks" / "segments.jsonl"
    buckets: dict[str, list[tuple[int, int]]] = {"paragraph": [], "section": [], "sentence": []}
    if src.exists():
        for line in src.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            rec = json.loads(line)
            stype = (rec.get("body") or {}).get("palimpsest:segmentType")
            if stype not in buckets:
                continue
            sel = (rec.get("target") or {}).get("selector") or {}
            a, e = sel.get("start"), sel.get("end")
            if not isinstance(a, int) or not isinstance(e, int):
                continue
            m = omap.remap_element(a, e)
            if m is not None:
                buckets[stype].append(m)

    def _segs(stype: str) -> list[Any]:
        return [
            Segment(segment_type=stype, index=i, start=s, end=e, text="")
            for i, (s, e) in enumerate(sorted(buckets[stype]))
        ]

    return _segs("paragraph"), _segs("section"), _segs("sentence")


def derive_subtext(
    parent: Project,
    workspace: Path,
    *,
    extraction_types: list[str],
    excluded_ids: list[str] | None = None,
    include_container_ids: list[str] | None = None,
    title: str = "",
    author: str = "",
    sep: str = SEPARATOR,
    progress: Callable[[str, str, float], None] | None = None,
) -> tuple[Project, LayoutConfig, dict[str, Any]]:
    """Build a child subtext project from the parent's kept extraction layers.

    ``include_container_ids`` optionally restricts extraction to elements lying within those
    container sections (e.g. an appendix), so "the Appendix books' chapters/footnotes" is one
    selection rather than thousands of manual deselections.

    ``progress(phase, message, fraction)`` is called at each real work boundary with a monotonic
    fraction in [0, 1), so callers can stream derivation progress (see the SSE derive endpoint).

    Returns ``(child_project, child_layout, summary)``. The caller (server) is responsible for
    writing the child's elements track from ``child_layout`` and any collection linking.
    """
    from palimpsest.project import ingest_file

    def _emit(phase: str, message: str, fraction: float) -> None:
        if progress is not None:
            progress(phase, message, fraction)

    cfg = load_layout(parent.path)
    if cfg is None:
        raise ValueError("Parent project has no layout configured")
    extraction = set(extraction_types)
    excluded = set(excluded_ids or [])
    container_ids = list(include_container_ids or [])
    container_spans: list[tuple[int, int]] | None = None
    if container_ids:
        by_id = {s.id: s for s in cfg.sections}
        resolved: list[tuple[int, int]] = []
        missing: list[str] = []
        for cid in container_ids:
            sec = by_id.get(cid)
            if sec is None or sec.end <= sec.start:
                missing.append(cid)
            else:
                resolved.append((sec.start, sec.end))
        if missing:
            raise ValueError(f"Unknown or empty container section(s): {', '.join(missing)}")
        container_spans = resolved
    spans = compute_kept_spans(cfg.sections, extraction, excluded, container_spans)
    if not spans:
        raise ValueError("No text matched the selected extraction layers")
    _emit("scan", "Computing kept regions…", 0.04)

    parent_text = parent.reference_text()
    omap = OffsetMap(spans, len(sep))
    child_text = assemble_text(parent_text, spans, sep)
    _emit("assemble", "Assembling subtext text…", 0.10)
    segmentation = _remap_parent_segments(parent.path, omap)
    _emit("segment", "Remapping segmentation…", 0.16)

    source_name = _subtext_source_name(parent.metadata.id, extraction_types, container_ids)
    child = ingest_file(
        Path(source_name),  # virtual path — content comes from text_extractor below
        workspace,
        title=title or f"{parent.metadata.title} — core",
        author=author or (parent.metadata.author or ""),
        language=parent.metadata.language,
        source_name=source_name,
        text_extractor=lambda _p: child_text,
        overwrite=True,
        segmentation=segmentation,
        pre_normalized=True,  # child_text is already-normalized parent slices; see ingest_file
        # ingest's own phase fractions occupy the [0.18, 0.48] slice of the overall derive.
        progress=lambda _ph, msg, fr: _emit("write", msg, 0.18 + fr * 0.30),
    )

    child_cfg = remap_layout(cfg.sections, cfg.mask_by_type, cfg.extra_types, omap)
    save_layout(child.path, child_cfg)
    _emit("layout", "Writing child layout…", 0.52)

    # Verse index: remap (preserves book/chapter/verse so the verse-number layer stays masked).
    verses_path = parent.path / "tracks" / "verses.jsonl"
    verse_count = 0
    if verses_path.exists():
        recs = [json.loads(line) for line in verses_path.read_text(encoding="utf-8").splitlines() if line.strip()]
        child_verses = remap_verses(recs, omap)
        verse_count = len(child_verses)
        _write_jsonl(child.path / "tracks" / "verses.jsonl", child_verses)
    _emit("verses", "Remapping verse index…", 0.56)

    def _on_track(done: int, total: int, name: str) -> None:
        # Spread the (variable) annotation-track remapping across the [0.58, 0.92] slice.
        _emit("tracks", f"Remapping {name}…", 0.58 + (done / max(1, total)) * 0.34)

    tracks_written = _remap_tracks(parent.path, child.path, omap, on_track=_on_track)
    _update_metadata(child.path, parent, extraction_types, list(excluded), sep)
    _emit("finalize", "Finalizing metadata…", 0.94)

    summary = {
        "project_id": child.metadata.id,
        "title": child.metadata.title,
        "parent_project_id": parent.metadata.id,
        "kept_spans": len(spans),
        "char_count": omap.child_len,
        "element_count": len(child_cfg.sections),
        "verse_count": verse_count,
        "tracks_remapped": tracks_written,
        "extraction_types": list(extraction_types),
        "container_ids": container_ids,
    }
    return child, child_cfg, summary
