"""Subtext derivation — materialize a filtered child project from a parent's kept layers.

Keeping an "extraction" type-layer (e.g. ``chapter``) pulls those element spans' text into a
new child project. Every parent layer that OVERLAPS the kept spans — the ``book``/``volume``/
``body`` containers, the verse-number index, and annotation tracks — is remapped onto the
child through a single piecewise offset map, preserving each layer's mask state (verse numbers
stay masked, exactly as in the parent). Non-overlapping elements (headers, front matter) fall
away. The child is an ordinary project (built via the standard ingest pipeline) plus a parent
link in its metadata.
"""
from __future__ import annotations

import dataclasses
import json
from pathlib import Path
from typing import TYPE_CHECKING, Any

from palimpsest.layout import LayoutConfig, LayoutSection, load_layout, save_layout

if TYPE_CHECKING:
    from palimpsest.project import Project

SEPARATOR = "\n\n"

# Tracks that are structural/derived and must NOT be naively offset-remapped: segments and
# sections are regenerated by ingest; elements is regenerated from the layout; verses is
# remapped specially (it carries book/chapter/verse metadata).
_SKIP_TRACKS = {"segments", "sections", "elements", "verses"}


class OffsetMap:
    """Piecewise parent→child offset translation over ordered, disjoint kept spans.

    Child text is ``SEPARATOR.join(parent_text[s:e] for (s,e) in spans)``; this maps a parent
    offset to its child offset, and maps a parent element to the single child element spanning
    its overlapped kept region (including the separator gaps between kept spans).
    """

    def __init__(self, spans: list[tuple[int, int]], sep_len: int) -> None:
        self.spans = spans
        self.sep_len = sep_len
        self.base: list[int] = []
        cursor = 0
        for i, (s, e) in enumerate(spans):
            self.base.append(cursor)
            cursor += (e - s) + (sep_len if i < len(spans) - 1 else 0)
        self.child_len = cursor

    def translate_point(self, off: int) -> int | None:
        """Child offset for a parent offset inside a kept span, else None (in a dropped gap)."""
        for i, (s, e) in enumerate(self.spans):
            if s <= off <= e:
                return self.base[i] + (off - s)
        return None

    def remap_element(self, a: int, e: int) -> tuple[int, int] | None:
        """Child [start,end) for a parent element [a,e), spanning every kept span it overlaps
        (separator gaps included), or None if it touches no kept span."""
        over = [(i, s, en) for i, (s, en) in enumerate(self.spans) if s < e and en > a]
        if not over:
            return None
        i0, s0, _ = over[0]
        iN, sN, eN = over[-1]
        cs = self.base[i0] + (max(a, s0) - s0)
        ce = self.base[iN] + (min(e, eN) - sN)
        return (cs, ce)


def compute_kept_spans(
    sections: list[LayoutSection], extraction_types: set[str], excluded_ids: set[str]
) -> list[tuple[int, int]]:
    """Ordered, merged spans of the extraction-layer elements (minus Stage-2 exclusions)."""
    raw = sorted(
        (s.start, s.end)
        for s in sections
        if s.type in extraction_types and s.id not in excluded_ids and s.start < s.end
    )
    merged: list[tuple[int, int]] = []
    for s, e in raw:
        if merged and s <= merged[-1][1]:
            merged[-1] = (merged[-1][0], max(merged[-1][1], e))
        else:
            merged.append((s, e))
    return merged


def assemble_text(parent_text: str, spans: list[tuple[int, int]], sep: str = SEPARATOR) -> str:
    return sep.join(parent_text[s:e] for s, e in spans)


def remap_layout(
    sections: list[LayoutSection],
    mask_by_type: dict[str, bool],
    extra_types: list[dict[str, Any]],
    omap: OffsetMap,
) -> LayoutConfig:
    """Carry every parent layout element overlapping a kept span onto the child, remapped and
    with its mask state preserved. Parent-id references to dropped elements are cleared."""
    out: list[LayoutSection] = []
    kept_ids: set[str] = set()
    for s in sections:
        m = omap.remap_element(s.start, s.end)
        if m is None or m[1] <= m[0]:
            continue
        kept_ids.add(s.id)
        out.append(dataclasses.replace(s, start=m[0], end=m[1]))
    for s in out:
        if s.parent_id is not None and s.parent_id not in kept_ids:
            s.parent_id = None
    return LayoutConfig(
        sections=out, mask_by_type=dict(mask_by_type), applied=True, extra_types=list(extra_types or [])
    )


def remap_verses(records: list[dict[str, Any]], omap: OffsetMap) -> list[dict[str, Any]]:
    """Carry verse-index records within kept spans, remapping their ns/s/e offsets and keeping
    book/chapter/verse metadata so the child's verse-number layer stays masked as in the parent."""
    out: list[dict[str, Any]] = []
    for r in records:
        ns, s, e = omap.translate_point(r["ns"]), omap.translate_point(r["s"]), omap.translate_point(r["e"])
        if ns is None or s is None or e is None:
            continue
        out.append({**r, "ns": ns, "s": s, "e": e})
    return out


def remap_track_annotations(annotations: list[dict[str, Any]], omap: OffsetMap) -> list[dict[str, Any]]:
    """Remap W3C annotations fully within kept spans (drop any crossing a dropped gap)."""
    out: list[dict[str, Any]] = []
    for ann in annotations:
        sel = (ann.get("target") or {}).get("selector") or {}
        a, e = sel.get("start"), sel.get("end")
        if not isinstance(a, int) or not isinstance(e, int):
            continue
        m = omap.remap_element(a, e)
        if m is None or (m[1] - m[0]) != (e - a):  # length change ⇒ crossed a dropped gap
            continue
        new = json.loads(json.dumps(ann))
        new["target"]["selector"]["start"] = m[0]
        new["target"]["selector"]["end"] = m[1]
        out.append(new)
    return out


def _subtext_source_name(parent_id: str, extraction_types: list[str]) -> str:
    tag = "-".join(t for t in extraction_types) or "subtext"
    return f"{parent_id}--{tag}.txt"


def _remap_tracks(parent_dir: Path, child_dir: Path, omap: OffsetMap) -> list[str]:
    """Remap each non-structural annotation track from parent to child. Returns track names written."""
    written: list[str] = []
    src = parent_dir / "tracks"
    if not src.exists():
        return written
    dst = child_dir / "tracks"
    dst.mkdir(parents=True, exist_ok=True)
    for path in sorted(src.glob("*.jsonl")):
        name = path.stem
        if name in _SKIP_TRACKS:
            continue
        recs = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
        remapped = remap_track_annotations(recs, omap)
        if not remapped:
            continue
        (dst / f"{name}.jsonl").write_text(
            "\n".join(json.dumps(r) for r in remapped) + "\n", encoding="utf-8"
        )
        written.append(name)
    return written


def _write_jsonl(path: Path, records: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        ("\n".join(json.dumps(r) for r in records) + "\n") if records else "", encoding="utf-8"
    )


def _update_metadata(child_dir: Path, parent: Project, extraction_types: list[str], excluded_ids: list[str], sep: str) -> None:
    meta_path = child_dir / "metadata.json"
    meta = json.loads(meta_path.read_text(encoding="utf-8"))
    meta["parent_project_id"] = parent.metadata.id
    meta["parent_reference_sha256"] = parent.metadata.reference_sha256
    meta["ingest_method"] = "subtext_derivation"
    meta["derivation"] = {
        "extraction_types": list(extraction_types),
        "excluded_ids": list(excluded_ids),
        "separator": sep,
    }
    meta_path.write_text(json.dumps(meta, indent=2, ensure_ascii=False), encoding="utf-8")


def derive_subtext(
    parent: Project,
    workspace: Path,
    *,
    extraction_types: list[str],
    excluded_ids: list[str] | None = None,
    title: str = "",
    author: str = "",
    sep: str = SEPARATOR,
) -> tuple[Project, LayoutConfig, dict[str, Any]]:
    """Build a child subtext project from the parent's kept extraction layers.

    Returns ``(child_project, child_layout, summary)``. The caller (server) is responsible for
    writing the child's elements track from ``child_layout`` and any collection linking.
    """
    from palimpsest.project import ingest_file

    cfg = load_layout(parent.path)
    if cfg is None:
        raise ValueError("Parent project has no layout configured")
    extraction = set(extraction_types)
    excluded = set(excluded_ids or [])
    spans = compute_kept_spans(cfg.sections, extraction, excluded)
    if not spans:
        raise ValueError("No text matched the selected extraction layers")

    parent_text = parent.reference_text()
    omap = OffsetMap(spans, len(sep))
    child_text = assemble_text(parent_text, spans, sep)

    source_name = _subtext_source_name(parent.metadata.id, extraction_types)
    child = ingest_file(
        Path(source_name),  # virtual path — content comes from text_extractor below
        workspace,
        title=title or f"{parent.metadata.title} — core",
        author=author or (parent.metadata.author or ""),
        language=parent.metadata.language,
        source_name=source_name,
        text_extractor=lambda _p: child_text,
        overwrite=True,
    )

    child_cfg = remap_layout(cfg.sections, cfg.mask_by_type, cfg.extra_types, omap)
    save_layout(child.path, child_cfg)

    # Verse index: remap (preserves book/chapter/verse so the verse-number layer stays masked).
    verses_path = parent.path / "tracks" / "verses.jsonl"
    verse_count = 0
    if verses_path.exists():
        recs = [json.loads(line) for line in verses_path.read_text(encoding="utf-8").splitlines() if line.strip()]
        child_verses = remap_verses(recs, omap)
        verse_count = len(child_verses)
        _write_jsonl(child.path / "tracks" / "verses.jsonl", child_verses)

    tracks_written = _remap_tracks(parent.path, child.path, omap)
    _update_metadata(child.path, parent, extraction_types, list(excluded), sep)

    summary = {
        "project_id": child.metadata.id,
        "title": child.metadata.title,
        "parent_project_id": parent.metadata.id,
        "kept_spans": len(spans),
        "char_count": omap.child_len,
        "element_count": len(child_cfg.sections),
        "verse_count": verse_count,
        "tracks_remapped": tracks_written,
        "extraction_types": list(extraction_types),
    }
    return child, child_cfg, summary
