#!/usr/bin/env python3
"""Phase 0 · P0.4b — majority-consensus OCR archaic witness (independent).

Standalone companion to ``detect_sources.py`` / ``detect_s_dismas.py`` (which we must
NOT touch, to avoid races). Produces an INDEPENDENT archaic Douay-Rheims witness derived
purely from OCR of the original 1582/1609/1610 page scans — the axis that lets the
downstream consensus (build_consensus.py) *corroborate*, not merely gap-fill, every
element. Critically, it is the ONLY archaic witness covering the archaic-gap OT books
absent from both s-dismas and odr-com: Ecclesiasticus + the twelve/major prophets.

Method — content-anchored attestation (NOT from-scratch OCR verse segmentation):
  Segmenting noisy blackletter OCR into verses from scratch is intractable, so we ANCHOR
  on the known modern text (Madueke_A; Sabates_A for the 3 appendix books it lacks) and
  CORROBORATE each verse in the OCR:

  1. Build a folded-token list ONCE per OCR product per alias:
       * our-ocr  — our fresh tesseract, page .txt files concatenated in page order.
       * djvu     — archive.org's whole-tome djvu OCR (one file per alias).
       * hocr     — archive.org's positional hOCR (ocrx_word text, one file per alias).
     The shared skeleton fold (ocr_sample.skel: long-s / u-v / i-j / vv-w / ligature /
     silent-e / doubled-letter) bridges archaic PRINT spelling to Madueke's MODERN
     spelling, so recall is a corroboration signal.

  2. Empirically resolve, per book, the best-covering alias for each product by probing a
     representative mid-chapter's folded profile against every candidate alias (exactly
     ocr_validate.py / ocr_sample.py's coverage-resolution). This dodges the ambiguous
     scan<->edition mapping (ot1 = early OT, ot2 = Psalms→Machabees+prophets, etc.).

  3. Walk the skeleton in canonical order. For each book, locate its region in each
     product; for each chapter, advance a MOVING CURSOR (monotone anchoring — never a
     global search per verse); for each verse, slide a probe-sized window (best_window)
     over the local neighbourhood and measure folded-token recall.

  4. A verse is attested by a product iff its folded-token recall in the located window
     exceeds ATTEST_THRESHOLD. FUSE the three products per verse — majority corroboration:
     count how many attest, consensus surface = the best-recall window's raw OCR text
     (preferring our-ocr, the freshly generated axis), record which products corroborated.

  Emit a read ONLY for attested verses (present=True). Reads → scratch (gitignored);
  validation summary → tracked JSON.

Deterministic + re-runnable: no randomness; identical inputs → identical output. The
our-ocr axis is generated by a background job (ocr_fulltome.py); before FINALISING we poll
its manifest until status=="complete", but develop/run against whatever pages already
exist and report the coverage honestly.

Run:  core/.venv/bin/python detect_ocr_consensus.py
      core/.venv/bin/python detect_ocr_consensus.py --book isaie      # single book (debug)
      core/.venv/bin/python detect_ocr_consensus.py --no-wait          # skip manifest poll
"""
from __future__ import annotations

import argparse
import html as _html
import json
import re
import sys
import time
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent                 # .../originaldr_reconstruction
MASK_ENGINE = HERE.parent                              # .../mask_engine
sys.path.insert(0, str(MASK_ENGINE))
sys.path.insert(0, str(MASK_ENGINE / "originaldr_validation"))

# shared archaic<->modern skeleton fold + windowing, reused from the validation harness.
from ocr_sample import skel, raw_words, best_window  # type: ignore[import]  # noqa: E402

# repo root: HERE.parents = [0]mask_engine [1]gold [2]fixtures [3]tests [4]core [5]<repo>
REPO = HERE.parents[5]
SCRATCH = REPO / "core/.scratch/originaldr-project"
OUR_OCR_ROOT = SCRATCH / "sources/our-ocr"
DJVU_DIR = SCRATCH / "sources/archive-org"
HOCR_ROOT = REPO / "imports/Scripture/Bibles/DouayRheims_DR/archive-org"
READS_DIR = SCRATCH / "reconstruction/reads"
OUT_READS = READS_DIR / "ocr_consensus.json"
OUT_VALID = HERE / "ocr-consensus-validation.json"
MANIFEST = HERE / "acquisition/our-ocr-manifest.json"

MADUEKE_READS = READS_DIR / "madueke_a.json"
SABATES_READS = READS_DIR / "sabates_a.json"      # covers the 3 appendix books madueke lacks

SKELETON = json.loads((HERE / "skeleton.json").read_text())
_BOOK_CH = {b["slug"]: b["chapters"] for b in SKELETON["books"]}
_BOOK_ORDER = [b["slug"] for b in SKELETON["books"]]
_BOOK_TESTAMENT = {b["slug"]: b["testament"] for b in SKELETON["books"]}

# OCR alias candidates per testament (multiple scans exist; per-book probe picks the best).
OT_ALIASES = ["ot1-1609", "ot2-1610", "holiebible-ot1", "holiebible-ot2"]
NT_ALIASES = ["nt-1582", "newtestament"]


def candidate_aliases(book: str) -> list[str]:
    """Alias set to probe for a book. APPENDIX apocrypha (prayer-of-manasses, 3-esdras,
    4-esdras) are printed at the END of the OT volumes (empirically strongest in ot2-1610 /
    holiebible-ot2), so they search the OT aliases, NOT the NT aliases."""
    return NT_ALIASES if _BOOK_TESTAMENT.get(book) == "NT" else OT_ALIASES

# The three independent OCR products fused into the consensus witness.
PRODUCTS = ("our-ocr", "djvu", "hocr")

# --- tunable, justified below in the validation record ---
ATTEST_THRESHOLD = 0.5     # folded type-recall in the located window to call a verse OCR-attested
BOOK_ALIAS_FLOOR = 0.35    # min mid-chapter probe recall for a product/alias to COVER a book
NEIGHBOURHOOD = 1200       # fallback chapter-window width when a chapter has no probe tokens
CHAP_PAD = 400             # tokens padded either side of a located chapter window (absorbs OCR
                           # running-head / marginal duplication that reorders verses within a chapter)
MANIFEST_POLL_S = 30       # seconds between manifest polls while waiting for our-ocr completion
MANIFEST_MAX_WAIT_S = 3 * 3600   # cap the wait; then proceed with whatever pages exist

# archaic-gap OT books: the primary purpose of this witness — no other archaic witness
# (s-dismas, odr-com) covers them, so OCR is their sole archaic corroboration.
ARCHAIC_GAP_OT = ["ecclesiasticus", "isaie", "jeremie", "ezechiel", "osee", "joel", "amos",
                  "abdias", "micheas", "nahum", "habacuc", "aggeus", "zacharias", "malachie"]


# ------------------------------------------------------------------ #
# Anchor (expected modern text per skeleton coordinate)
# ------------------------------------------------------------------ #
def load_anchor() -> dict[str, str]:
    """{skeleton_id: modern surface}. Madueke_A is primary; Sabates_A fills the 3
    appendix books (prayer-of-manasses, 3-esdras, 4-esdras) madueke lacks."""
    anchor: dict[str, str] = {}
    for path in (SABATES_READS, MADUEKE_READS):      # madueke last → wins on overlap
        if not path.exists():
            continue
        blob = json.loads(path.read_text())
        for r in blob.get("reads", []):
            sk = r.get("skeleton_id", "")
            if sk.startswith("scripture/"):
                anchor[sk] = r.get("surface", "")
    return anchor


def anchor_by_book(anchor: dict[str, str]) -> dict[str, dict[int, dict[int, str]]]:
    """book -> {chapter -> {verse -> modern surface}}."""
    out: dict[str, dict[int, dict[int, str]]] = defaultdict(lambda: defaultdict(dict))
    for sk, surf in anchor.items():
        parts = sk.split("/")
        if len(parts) != 4:
            continue
        _, book, ch, v = parts
        try:
            out[book][int(ch)][int(v)] = surf
        except ValueError:
            continue
    return out


# ------------------------------------------------------------------ #
# OCR products: build a folded-token list AND a parallel raw-word list per alias.
# We keep raw words alongside the folded tokens (index-aligned) so the stored archaic
# `surface` is genuine OCR text sliced by the same window bounds best_window returns.
# ------------------------------------------------------------------ #
_WORD_RE = re.compile(r"[A-Za-zÆæŒœ]+")
_OCRX = re.compile(r'<span class="ocrx_word"[^>]*>([^<]*)</span>')


def _fold_aligned(text: str) -> tuple[list[str], list[str]]:
    """Return (folded_tokens, raw_words) index-aligned; drop tokens whose fold is <2 chars
    (matches sk_list's len>=2 filter so window bounds line up with sk_list-based probes)."""
    raws = _WORD_RE.findall(text)
    folded: list[str] = []
    kept_raw: list[str] = []
    for w in raws:
        s = skel(w)
        if len(s) >= 2:
            folded.append(s)
            kept_raw.append(w)
    return folded, kept_raw


def load_our_ocr(alias: str) -> tuple[list[str], list[str], int]:
    """Concatenate our fresh tesseract page .txt files (page order) → (folded, raw, n_pages)."""
    d = OUR_OCR_ROOT / alias
    if not d.is_dir():
        return [], [], 0
    pages = sorted(d.glob("*.txt"))
    text = "\n".join(p.read_text(encoding="utf-8", errors="replace") for p in pages)
    folded, raw = _fold_aligned(text)
    return folded, raw, len(pages)


def load_djvu(alias: str) -> tuple[list[str], list[str]]:
    p = DJVU_DIR / f"{alias}_djvu.txt"
    if not p.exists():
        return [], []
    return _fold_aligned(p.read_text(encoding="utf-8", errors="replace"))


def load_hocr(alias: str) -> tuple[list[str], list[str]]:
    d = HOCR_ROOT / alias
    if not d.is_dir():
        return [], []
    files = sorted(d.glob("*_hocr.html"))
    if not files:
        return [], []
    text = files[0].read_text(encoding="utf-8", errors="replace")
    words = [_html.unescape(w) for w in _OCRX.findall(text)]
    folded: list[str] = []
    kept_raw: list[str] = []
    for w in words:
        # an ocrx_word may carry trailing punctuation; the raw-word regex re-splits it.
        for rw in _WORD_RE.findall(w):
            s = skel(rw)
            if len(s) >= 2:
                folded.append(s)
                kept_raw.append(rw)
    return folded, kept_raw


class Product:
    """One loaded OCR product for one alias: folded tokens + index-aligned raw words.
    Deliberately holds NO precomputed set of the whole folded list — every window search
    (locate_region/tight_window) sets only its small window slice, so a whole-list set would
    just double memory for no benefit (18 product token-lists are held at once)."""

    __slots__ = ("name", "alias", "folded", "raw", "n_pages")

    def __init__(self, name: str, alias: str, folded: list[str], raw: list[str], n_pages: int = 0):
        self.name = name
        self.alias = alias
        self.folded = folded
        self.raw = raw
        self.n_pages = n_pages


# ------------------------------------------------------------------ #
# Content-anchored windowing (monotone chapter cursor; fresh per-verse window)
# ------------------------------------------------------------------ #
def _probe(text: str) -> list[str]:
    return [s for s in (skel(w) for w in raw_words(text)) if len(s) >= 2]


def _recall(probe: list[str], hay: list[str], start: int, end: int) -> float:
    pset = set(probe)
    if not pset:
        return 0.0
    return len(pset & set(hay[start:end])) / len(pset)


def locate_region(probe: list[str], folded: list[str], lo: int = 0) -> tuple[float, int, int]:
    """Best-recall expanded window for `probe` inside folded[lo:], returned in ABSOLUTE
    indices. Thin wrapper over the shared best_window (which returns coarse recall + bounds
    in the SLICE's coordinates) that re-bases to absolute and recomputes recall on the
    expanded window so the returned recall matches the stored surface's span."""
    sub = folded[lo:]
    _, s, e = best_window(probe, sub)
    a, b = lo + s, lo + e
    return _recall(probe, folded, a, b), a, b


def tight_window(probe: list[str], folded: list[str], lo: int, hi: int) -> tuple[float, int, int]:
    """Locate a VERSE-SIZED window (not the expanded region) for the stored diplomatic
    surface: slide a probe-length window (min 12) over folded[lo:hi] and return the
    max-recall offset with NO expansion, so the surface tracks the verse extent rather than
    over-running into neighbours. Returns (recall, abs_start, abs_end)."""
    hi = min(hi, len(folded))
    if lo >= hi:
        return 0.0, lo, lo
    pset = set(probe)
    if not pset:
        return 0.0, lo, lo
    w = max(len(probe), 12)
    step = max(1, w // 6)
    best_rec, best_off = 0.0, lo
    for off in range(lo, max(lo + 1, hi - w + 1), step):
        rec = len(pset & set(folded[off:off + w])) / len(pset)
        if rec > best_rec:
            best_rec, best_off = rec, off
    return best_rec, best_off, min(hi, best_off + w)


def resolve_book_alias(book: str, chapters: dict[int, dict[int, str]],
                       products_by_alias: dict[str, dict[str, Product]]
                       ) -> dict[str, tuple[str, float]]:
    """For each product, pick the alias whose mid-chapter probe-recall is highest, but only
    if that recall clears BOOK_ALIAS_FLOOR — otherwise the product does NOT cover this book
    (guards against a partially-OCR'd our-ocr wrongly matching the wrong volume, e.g. Isaie
    spuriously matching ot1-1609 Kings text). Returns {product: (alias, probe_recall)};
    ("", 0.0) means uncovered."""
    aliases = candidate_aliases(book)
    chs = sorted(chapters)
    if not chs:
        return {p: ("", 0.0) for p in PRODUCTS}
    mid = chs[len(chs) // 2]
    probe = _probe(" ".join(chapters[mid][v] for v in sorted(chapters[mid])))
    chosen: dict[str, tuple[str, float]] = {}
    for prod in PRODUCTS:
        best_alias, best_rec = "", 0.0
        for alias in aliases:
            p = products_by_alias.get(alias, {}).get(prod)
            if p is None or not p.folded:
                continue
            rec, _, _ = locate_region(probe, p.folded)
            if rec > best_rec:
                best_alias, best_rec = alias, rec
        chosen[prod] = (best_alias, round(best_rec, 4)) if best_rec >= BOOK_ALIAS_FLOOR else ("", round(best_rec, 4))
    return chosen


# ------------------------------------------------------------------ #
# Per-book detection
# ------------------------------------------------------------------ #
def read_record(skid: str, surface: str, locus: str, conf: str, evidence: str) -> dict:
    return {"skeleton_id": skid, "present": True, "surface": surface,
            "spelling": "archaic", "locus": locus, "method": "ocr-consensus",
            "local_confidence": conf, "evidence_ptr": evidence}


def confidence_for(depth: int, best_recall: float) -> str:
    """local_confidence keys off corroboration depth × recall of the winning product."""
    if depth >= 3 and best_recall >= 0.6:
        return "high"
    if depth >= 2 and best_recall >= 0.55:
        return "high"
    if depth >= 2 or best_recall >= 0.7:
        return "moderate"
    return "low"


def detect_book(book: str, chapters: dict[int, dict[int, str]],
                products_by_alias: dict[str, dict[str, Product]]
                ) -> tuple[list[dict], dict]:
    """Attest every verse of one book across the 3 OCR products.

    Per product: resolve the best-covering alias, then walk chapters with a monotone
    CHAPTER cursor (each chapter located once, padded), searching every verse FRESH within
    its fixed chapter window. Returns (reads, book_stats); book_stats aggregates attestation
    + corroboration-depth + folded agreement-vs-anchor for the validation report.
    """
    resolved = resolve_book_alias(book, chapters, products_by_alias)
    alias_of = {prod: alias for prod, (alias, _) in resolved.items()}
    probe_recall_of = {prod: rec for prod, (_, rec) in resolved.items()}
    # active products (name -> Product) that actually COVER this book (cleared the floor)
    active: dict[str, Product] = {}
    for prod in PRODUCTS:
        alias = alias_of[prod]
        if alias:
            p = products_by_alias.get(alias, {}).get(prod)
            if p and p.folded:
                active[prod] = p

    reads: list[dict] = []
    depth_hist: Counter[int] = Counter()
    n_expected = sum(len(vs) for vs in chapters.values())
    n_attested = 0
    agree_matched = 0
    agree_denom = 0
    # per-product monotone CHAPTER cursor (absolute index into that product's folded list);
    # advanced only at chapter granularity, never per-verse (avoids intra-chapter drift).
    cursor = {prod: 0 for prod in active}

    maxch = _BOOK_CH.get(book, 0)
    for ch in sorted(chapters):
        if maxch and ch > maxch:      # anchor should never exceed the grid, but guard anyway
            continue
        verses = chapters[ch]
        # Locate the chapter's region once per product, then search each verse WITHIN that
        # fixed chapter window (verses may be OCR-reordered by repeated running-heads /
        # marginal duplication, so a per-verse forward cursor would drift — cf. aggeus). The
        # chapter cursor advances monotonically (O(book)); the window is padded generously so
        # intra-chapter verse jitter is still captured.
        chap_probe = _probe(" ".join(verses[v] for v in sorted(verses)))
        chap_region: dict[str, tuple[int, int]] = {}
        for prod, p in active.items():
            if not chap_probe:
                lo = cursor[prod]
                chap_region[prod] = (lo, min(len(p.folded), lo + NEIGHBOURHOOD))
                continue
            _, a, b = locate_region(chap_probe, p.folded, cursor[prod])
            ca = max(0, a - CHAP_PAD)
            cb = min(len(p.folded), b + CHAP_PAD)
            chap_region[prod] = (ca, cb)
            cursor[prod] = a       # advance monotonically to the chapter start (not the pad)

        for v in sorted(verses):
            skid = f"scripture/{book}/{ch}/{v}"
            probe = _probe(verses[v])
            if not probe:
                continue
            best_prod, best_rec = "", 0.0
            best_bounds: dict[str, tuple[int, int]] = {}
            attesters: list[str] = []
            for prod, p in active.items():
                ca, cb = chap_region[prod]
                # verse-sized best window searched FRESH within the fixed chapter window
                rec, wa, wb = tight_window(probe, p.folded, ca, cb)
                best_bounds[prod] = (wa, wb)
                if rec >= ATTEST_THRESHOLD:
                    attesters.append(prod)
                if rec > best_rec:
                    best_prod, best_rec = prod, rec

            depth = len(attesters)
            depth_hist[depth] += 1
            if depth == 0:
                continue
            n_attested += 1
            # consensus surface: prefer our-ocr among the attesters (freshly generated axis);
            # else the best-recall product's window.
            pick = next((pref for pref in ("our-ocr", "djvu", "hocr") if pref in attesters),
                        best_prod)
            p = active[pick]
            wa, wb = best_bounds[pick]
            surface = " ".join(p.raw[wa:wb]).strip()
            conf = confidence_for(depth, best_rec)
            locus = f"{p.alias} tok[{wa}:{wb}]"
            evid = f"ocr_consensus:{'+'.join(attesters)}:{book}:{ch}:{v}"
            reads.append(read_record(skid, surface, locus, conf, evid))
            # folded agreement of the consensus surface vs the modern anchor (both folded).
            m, d = _token_agreement(surface, verses[v])
            agree_matched += m
            agree_denom += d

    stats = {
        "book": book,
        "testament": _BOOK_TESTAMENT.get(book),
        "alias_resolution": {k: {"alias": alias_of[k], "probe_recall": probe_recall_of[k]}
                             for k in PRODUCTS},
        "active_products": sorted(active),
        "expected_verses": n_expected,
        "attested_verses": n_attested,
        "attestation_rate": round(n_attested / n_expected, 4) if n_expected else None,
        "corroboration_depth_hist": {str(k): v for k, v in sorted(depth_hist.items())},
        "folded_agreement_vs_anchor": round(agree_matched / agree_denom, 4) if agree_denom else None,
    }
    return reads, stats


# ------------------------------------------------------------------ #
# Folded agreement (consensus OCR surface vs modern anchor)
# ------------------------------------------------------------------ #
def _fold_multiset(text: str) -> Counter:
    return Counter(s for s in (skel(w) for w in raw_words(text)) if len(s) >= 2)


def _token_agreement(a: str, b: str) -> tuple[int, int]:
    """Folded-token multiset overlap; denom = max(|a|,|b|) (penalises drops AND leakage)."""
    ta, tb = _fold_multiset(a), _fold_multiset(b)
    inter = sum((ta & tb).values())
    denom = max(sum(ta.values()), sum(tb.values())) or 1
    return inter, denom


# ------------------------------------------------------------------ #
# Coverage (mirror detect_s_dismas.coverage)
# ------------------------------------------------------------------ #
def coverage(reads: list[dict]) -> dict:
    chapters, verses, out_of_grid = set(), 0, []
    books = set()
    for r in reads:
        parts = r["skeleton_id"].split("/")
        if len(parts) != 4 or parts[0] != "scripture":
            continue
        _, book, ch, _ = parts
        verses += 1
        books.add(book)
        chapters.add((book, int(ch)))
        maxch = _BOOK_CH.get(book)
        if maxch is None or int(ch) > maxch:
            out_of_grid.append(r["skeleton_id"])
    return {"books": len(books), "chapters": len(chapters), "verses": verses,
            "out_of_grid": out_of_grid[:20], "out_of_grid_count": len(out_of_grid)}


# ------------------------------------------------------------------ #
# our-ocr completion gate
# ------------------------------------------------------------------ #
def manifest_status() -> str | None:
    if not MANIFEST.exists():
        return None
    try:
        return json.loads(MANIFEST.read_text()).get("status")
    except Exception:  # noqa: BLE001
        return None


def wait_for_our_ocr(no_wait: bool) -> dict:
    """Poll the our-ocr manifest until complete (or the wait cap). Returns a status dict
    for the validation report — honest about whether we finalised on a complete tome."""
    if no_wait:
        return {"gated": False, "status": manifest_status(), "note": "--no-wait: not gated"}
    t0 = time.time()
    st = manifest_status()
    while st != "complete" and time.time() - t0 < MANIFEST_MAX_WAIT_S:
        elapsed = int(time.time() - t0)
        got = {a: len(list((OUR_OCR_ROOT / a).glob("*.txt"))) if (OUR_OCR_ROOT / a).is_dir() else 0
               for a in OT_ALIASES + NT_ALIASES}
        print(f"  [wait] our-ocr manifest status={st!r} elapsed={elapsed}s pages={got}", flush=True)
        time.sleep(MANIFEST_POLL_S)
        st = manifest_status()
    return {"gated": True, "status": st, "waited_s": round(time.time() - t0, 1),
            "complete": st == "complete",
            "note": "finalised on complete tome" if st == "complete"
            else "PROCEEDED without completion — coverage gap possible (see per_book)"}


# ------------------------------------------------------------------ #
def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--book", help="restrict to a single slug (debug)")
    ap.add_argument("--no-wait", action="store_true",
                    help="do not poll the our-ocr manifest (develop against current pages)")
    ap.add_argument("--no-validate", action="store_true")
    args = ap.parse_args()

    READS_DIR.mkdir(parents=True, exist_ok=True)

    gate = wait_for_our_ocr(args.no_wait)
    print(f"our-ocr gate: {gate['note']} (status={gate['status']})")

    anchor = load_anchor()
    by_book = anchor_by_book(anchor)

    books = _BOOK_ORDER if not args.book else [args.book]
    if args.book and args.book not in _BOOK_CH:
        raise SystemExit(f"no such book slug: {args.book}")

    # load every product for every alias ONCE (folded token lists are large; build once).
    print("loading OCR products (folding once per alias) ...", flush=True)
    products_by_alias: dict[str, dict[str, Product]] = defaultdict(dict)
    ocr_pages: dict[str, int] = {}
    for alias in OT_ALIASES + NT_ALIASES:
        of, oraw, npg = load_our_ocr(alias)
        products_by_alias[alias]["our-ocr"] = Product("our-ocr", alias, of, oraw, npg)
        ocr_pages[alias] = npg
        df, draw = load_djvu(alias)
        products_by_alias[alias]["djvu"] = Product("djvu", alias, df, draw)
        hf, hraw = load_hocr(alias)
        products_by_alias[alias]["hocr"] = Product("hocr", alias, hf, hraw)
        print(f"  {alias:16s} our-ocr={len(of):>7,}tok({npg}pg) "
              f"djvu={len(df):>7,}tok hocr={len(hf):>7,}tok", flush=True)

    all_reads: list[dict] = []
    per_book: list[dict] = []
    for book in books:
        chapters = by_book.get(book)
        if not chapters:
            per_book.append({"book": book, "testament": _BOOK_TESTAMENT.get(book),
                             "expected_verses": 0, "attested_verses": 0,
                             "note": "no modern anchor for this book"})
            continue
        reads, stats = detect_book(book, chapters, products_by_alias)
        all_reads.extend(reads)
        per_book.append(stats)
        rate = stats["attestation_rate"]
        print(f"{book:22s} {stats['attested_verses']:5d}/{stats['expected_verses']:<5d} "
              f"verses ({rate if rate is not None else 'n/a'}) "
              f"agree={stats['folded_agreement_vs_anchor']} "
              f"prods={stats['active_products']}", flush=True)

    cov = coverage(all_reads)
    out = {"source": "ocr_consensus", "lineage": "our-ocr", "independent": True,
           "spelling": "archaic", "count": len(all_reads), "coverage": cov,
           "reads": all_reads}
    OUT_READS.write_text(json.dumps(out, ensure_ascii=False))
    print(f"\nreads → {OUT_READS.relative_to(REPO)}  "
          f"({cov['books']} books · {cov['chapters']} chapters · {cov['verses']} verses"
          + (f" · ⚠ {cov['out_of_grid_count']} out-of-grid" if cov['out_of_grid_count'] else "")
          + ")")

    if not args.no_validate:
        val = build_validation(per_book, cov, gate, ocr_pages, bool(args.book))
        OUT_VALID.write_text(json.dumps(val, ensure_ascii=False, indent=2) + "\n")
        agg = val["aggregate"]
        print(f"\nvalidation: attested {agg['attested_verses']}/{agg['expected_verses']} "
              f"({agg['attestation_rate']}) · folded_agreement_vs_anchor={agg['folded_agreement_vs_anchor']}")
        print(f"  corroboration depth {agg['corroboration_depth_hist']}")
        ag = val["archaic_gap_ot"]
        print(f"  archaic-gap OT: attested {ag['attested_verses']}/{ag['expected_verses']} "
              f"({ag['attestation_rate']}) across {len(ag['per_book'])} books")
        if val["weak_books"]:
            print(f"  weak books ({len(val['weak_books'])}): "
                  + ", ".join(f"{b['book']}={b['attestation_rate']}" for b in val["weak_books"][:12]))
        print(f"validation → {OUT_VALID.relative_to(REPO)}")
    return 0


def build_validation(per_book: list[dict], cov: dict, gate: dict,
                     ocr_pages: dict[str, int], single_book: bool) -> dict:
    scored = [b for b in per_book if b.get("expected_verses")]
    exp = sum(b["expected_verses"] for b in scored)
    att = sum(b["attested_verses"] for b in scored)
    depth_hist: Counter[int] = Counter()
    am = ad = 0
    for b in scored:
        for k, n in b.get("corroboration_depth_hist", {}).items():
            depth_hist[int(k)] += n
        fa = b.get("folded_agreement_vs_anchor")
        if fa is not None:
            am += round(fa * b["attested_verses"])
            ad += b["attested_verses"]

    def _gap_agg() -> dict:
        gb = [b for b in per_book if b["book"] in ARCHAIC_GAP_OT and b.get("expected_verses")]
        e = sum(b["expected_verses"] for b in gb)
        a = sum(b["attested_verses"] for b in gb)
        return {"expected_verses": e, "attested_verses": a,
                "attestation_rate": round(a / e, 4) if e else None,
                "books_covered": [b["book"] for b in gb if b["attested_verses"] > 0],
                "books_missing": [b for b in ARCHAIC_GAP_OT
                                  if b not in {x["book"] for x in gb if x["attested_verses"] > 0}],
                "per_book": [{"book": b["book"], "expected": b["expected_verses"],
                              "attested": b["attested_verses"],
                              "attestation_rate": b["attestation_rate"],
                              "folded_agreement_vs_anchor": b.get("folded_agreement_vs_anchor")}
                             for b in gb]}

    weak = sorted(
        [b for b in scored if (b["attestation_rate"] or 0) < 0.5
         or (b.get("folded_agreement_vs_anchor") or 1) < 0.5],
        key=lambda b: (b["attestation_rate"] or 0))

    return {
        "witness": "ocr_consensus (majority-consensus archaic OCR of the 1582/1609/1610 scans)",
        "modern_anchor": "madueke_a (+ sabates_a for the 3 appendix books)",
        "method": {
            "approach": "content-anchored attestation — anchor on the modern text and "
                        "corroborate each verse in OCR; NOT from-scratch OCR verse segmentation.",
            "fold": "shared ocr_sample.skel: long-s / u-v / i-j / vv-w / ligature / silent-e / "
                    "doubled-letter — bridges archaic PRINT spelling to modern anchor spelling.",
            "products_fused": list(PRODUCTS),
            "product_notes": {
                "our-ocr": "our FRESH tesseract of the jp2 scans (independent 3rd OCR) — preferred "
                           "for the stored consensus surface when it attests.",
                "djvu": "archive.org whole-tome djvu OCR (one file per alias).",
                "hocr": "archive.org positional hOCR — ocrx_word text extracted.",
            },
            "windowing": "per book: empirically resolve the best-covering alias per product "
                         "(mid-chapter probe recall); walk skeleton in canonical order; moving "
                         "cursor per product; per-verse best_window over a bounded neighbourhood.",
            "attest_threshold": ATTEST_THRESHOLD,
            "attest_threshold_rationale":
                "folded TYPE-recall >= 0.5 in the located window. The fold is intentionally lossy "
                "(archaic<->modern), and blackletter OCR drops/garbles ~20-40% of tokens, so an "
                "exact-match rate is unattainable; 0.5 means a majority of the verse's distinctive "
                "modern tokens are corroborated in the print OCR — strong evidence the verse is "
                "attested — while rejecting incidental windows. Corroboration DEPTH (how many of "
                "the 3 products independently clear 0.5) is the fusion signal.",
            "consensus_surface": "raw OCR window text of the winning product (prefer our-ocr).",
            "determinism": "no randomness; identical inputs → identical output.",
        },
        "our_ocr_gate": gate,
        "our_ocr_pages_present": ocr_pages,
        "coverage": cov,
        "aggregate": {
            "books_with_anchor": len(scored),
            "expected_verses": exp,
            "attested_verses": att,
            "attestation_rate": round(att / exp, 4) if exp else None,
            "corroboration_depth_hist": {str(k): v for k, v in sorted(depth_hist.items())},
            "corroboration_depth_note":
                "counts of anchor verses by how many of the 3 OCR products independently cleared "
                "the recall threshold. depth 0 = unattested (NOT emitted as a read); depths 1-3 are "
                "the emitted reads (depth 3 = all three OCR products corroborate the verse).",
            "folded_agreement_vs_anchor": round(am / ad, 4) if ad else None,
            "single_book_debug_run": single_book,
        },
        "archaic_gap_ot": _gap_agg(),
        "weak_books": [{"book": b["book"], "testament": b.get("testament"),
                        "expected_verses": b["expected_verses"], "attested_verses": b["attested_verses"],
                        "attestation_rate": b["attestation_rate"],
                        "folded_agreement_vs_anchor": b.get("folded_agreement_vs_anchor"),
                        "active_products": b.get("active_products")}
                       for b in weak],
        "caveats": [
            "Recall is a CORROBORATION signal, not an exact-match rate: the archaic<->modern fold "
            "is lossy and blackletter OCR is noisy, so attestation confirms word-correspondence, "
            "not verbatim fidelity.",
            "The stored archaic `surface` is a raw OCR window sliced by folded-token bounds; it may "
            "over/under-run the exact verse extent (OCR carries no verse boundaries) and can include "
            "adjacent apparatus/marginalia. It is a diplomatic attestation snippet, not a clean verse.",
            "Verses whose modern anchor is short/function-word-heavy are harder to attest (few "
            "distinctive tokens) and may fall below threshold despite being present.",
            "our-ocr coverage depends on the background ocr_fulltome job; if it was incomplete at "
            "finalisation (see our_ocr_gate/our_ocr_pages_present), affected aliases fall back to "
            "djvu+hocr corroboration only (depth capped at 2 there).",
        ],
        "per_book": per_book,
    }


if __name__ == "__main__":
    sys.exit(main())
